#!/usr/bin/env sh

# limelight -m config width 1
# limelight -m config radius 5 
# limelight -m config placement exterior
# limelight -m config active_color 0xBFA1EFD3
# limelight -m config normal_color 0x00a6b3cc

# echo "limelight configuration loaded.."
